spring:
  datasource:
    username: keycloak
    url: jdbc:postgresql://localhost:5432/keycloak
    password: keycloak
  sql:
    init:
      mode: always
      platform: postgres
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

hbo:
  credit:
    file:
      path: file://${HOME}/shiva/mywork/assignment/dada/archive/credits.csv
  title:
    file:
      path: file://${HOME}/shiva/mywork/assignment/dada/archive/titles.csv
