server:
  port: '8040'

spring:
  datasource:
    username: dear
    password: comrade
    url: jdbc:postgresql://172.19.0.2:5432/dear_comrade
    #url: jdbc:postgresql://localhost:5432/dear_comrade
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#  sql:
#    init:
#      mode: ALWAYS
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: ALWAYS
springdoc:
  swagger-ui:
    path: /swagger-ui.html
